// catch error
function catchError(error) {
  console.error('Error', error)
}